[package]
name = "git-calendar"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
scraper = "0.22.0"
serde_json = "1.0.133"
time = { version = "0.3.37", features = ["macros", "parsing"] }
